### ISSUE TITLE
Release and use in production

### ISSUE THREAD

**Issue by dmitrii-esin** [spiderpoul/redux-blaze#1]
Hi!
What do we need to update versions up to 1.0.0?

**Comment by spiderpoul** [comment]
Hi! It's ready for use in production. Is it required to have 1.0.0 version? F.e. `axios` still have 0.19.2 version

**Comment by sunndeath** [comment]
> Hi! It's ready for use in production. Is it required to have 1.0.0 version? F.e. `axios` still have 0.19.2 version

Ok, thanks for the reply!

**Comment by dmitrii-esin** [comment]
> Hi! It's ready for use in production. Is it required to have 1.0.0 version? F.e. `axios` still have 0.19.2 version

Ok, thanks for the reply!
